on:
  push:
    branches:
    - main
 
jobs:

  build:

    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git project
      uses: actions/checkout@v3.5.2
    - name: Docker Login
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  #    uses: docker/login-action@v2.1.0
  #    with:
   #     registry: ghcr.io
   #     username: ketsapiwiq
   #     password: $GITHUB_TOKEN
#    - name: Login Github
      run: docker login -u ketsapiwiq -p $GITHUB_TOKEN ghcr.io
      
    - name: Build l'image
      run: docker build -t ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME
      
    - name: Push dans le registre Github
      run: docker push ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME
      
