on:
  push:

jobs:
  build:
    name: Build Docker image
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Git project
      uses: actions/checkout@v3.5.2
    - name: Docker Login
      env:
        PUSH_IMAGE: ${{ secrets.PUSH_IMAGE }}
      run: docker login -u ketsapiwiq -p $PUSH_IMAGE ghcr.io
      
    - name: Build l'image
      run: docker build -t ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME .
      
    - name: Push dans le registre Github
      run: docker push ghcr.io/$GITHUB_REPOSITORY:$GITHUB_REF_NAME
      
